export const categories = [
  "All",
  "UI Components",
  "Design Systems",
  "Resources & Tools",
  "Typography",
  "Animation",
  "Inspiration",
  "Media",
];

export const sites = [
  {
    name: "Shadcn UI",
    url: "https://ui.shadcn.com/",
    category: "UI Components",
    description:
      "Beautifully designed components that you can copy and paste into your apps.",
    imageSlug: "shadcn-ui",
  },
  {
    name: "8bitCN",
    url: "https://www.8bitcn.com/",
    category: "Resources & Tools",
    description: "Pixel art and 8-bit style resources.",
    imageSlug: "8bitcn",
  },
  {
    name: "Aceternity UI",
    url: "https://ui.aceternity.com/",
    category: "UI Components",
    description:
      "Copy paste the most trending components and use them in your websites without having to worry about styling.",
    imageSlug: "aceternity-ui",
  },
  {
    name: "SmoothUI",
    url: "https://smoothui.dev/",
    category: "UI Components",
    description: "Smooth and modern UI components for React.",
    imageSlug: "smoothui",
  },
  {
    name: "TweakCN",
    url: "https://tweakcn.com/",
    category: "Resources & Tools",
    description: "A tool to tweak and customize Shadcn components easily.",
    imageSlug: "tweakcn",
  },
  {
    name: "MagicUI",
    url: "https://magicui.design/",
    category: "UI Components",
    description:
      "UI Library for Design Engineers. Animated components and effects.",
    imageSlug: "magicui",
  },
  {
    name: "Fonttrio",
    url: "https://www.fonttrio.xyz/",
    category: "Typography",
    description: "Curated typography pairings and font inspiration.",
    imageSlug: "fonttrio",
  },
  {
    name: "Shadcnblocks",
    url: "https://www.shadcnblocks.com/",
    category: "Resources & Tools",
    description: "Pre-built website blocks using Shadcn UI components.",
    imageSlug: "shadcnblocks",
  },
  {
    name: "Shadcn Studio",
    url: "https://shadcnstudio.com/",
    category: "Design Systems",
    description: "Visual builder for Shadcn UI.",
    imageSlug: "shadcn-studio",
  },
  {
    name: "Reactbits",
    url: "https://reactbits.dev/",
    category: "UI Components",
    description: "A collection of interactive React components.",
    imageSlug: "reactbits",
  },
  {
    name: "Tailark",
    url: "https://tailark.com/",
    category: "UI Components",
    description: "Tailwind CSS UI blocks and templates.",
    imageSlug: "tailark",
  },
  {
    name: "Kibo UI",
    url: "https://www.kibo-ui.com/",
    category: "UI Components",
    description: "Minimalist and accessible React components.",
    imageSlug: "kibo-ui",
  },
  {
    name: "Kokonut UI",
    url: "https://kokonutui.com/",
    category: "UI Components",
    description: "A fresh set of UI components for modern web apps.",
    imageSlug: "kokonut-ui",
  },
  {
    name: "Animate UI",
    url: "https://animate-ui.com/",
    category: "Animation",
    description: "Ready to use CSS animations and effects.",
    imageSlug: "animate-ui",
  },
  {
    name: "Craftwork",
    url: "https://craftwork.design/",
    category: "Inspiration",
    description: "High-quality UX/UI and web design resources.",
    imageSlug: "craftwork",
  },
  {
    name: "One Page Love",
    url: "https://onepagelove.com/",
    category: "Inspiration",
    description: "The ultimate showcase of beautiful One Page websites.",
    imageSlug: "one-page-love",
  },
  {
    name: "Get Design.md",
    url: "https://getdesign.md/",
    category: "Design Systems",
    description: "Markdown-based design system documentation.",
    imageSlug: "get-design-md",
  },
  {
    name: "Component Gallery",
    url: "https://component.gallery/",
    category: "Design Systems",
    description: "A repository of components based on top design systems.",
    imageSlug: "component-gallery",
  },
  {
    name: "Mobbin",
    url: "https://mobbin.com/",
    category: "Inspiration",
    description: "The world's largest UI and UX reference library.",
    imageSlug: "mobbin",
  },
  {
    name: "Rebrand Gallery",
    url: "https://www.rebrand.gallery/",
    category: "Inspiration",
    description: "A gallery of brand identity redesigns.",
    imageSlug: "rebrand-gallery",
  },
  {
    name: "HTMLRev",
    url: "https://htmlrev.com/",
    category: "Inspiration",
    description: "Free HTML templates for websites and landing pages.",
    imageSlug: "htmlrev",
  },
  {
    name: "Flowbite",
    url: "https://flowbite.com/",
    category: "UI Components",
    description:
      "Build websites even faster with components on top of Tailwind CSS.",
    imageSlug: "flowbite",
  },
  {
    name: "unDraw",
    url: "https://undraw.co/",
    category: "Media",
    description:
      "Open-source illustrations for any idea you can imagine and create.",
    imageSlug: "undraw",
  },
  {
    name: "Animista",
    url: "https://animista.net/",
    category: "Animation",
    description: "CSS animations on demand.",
    imageSlug: "animista",
  },
  {
    name: "Lineicons",
    url: "https://lineicons.com/",
    category: "Resources & Tools",
    description: "Free line icons for designers and developers.",
    imageSlug: "lineicons",
  },
  {
    name: "Coolors",
    url: "https://coolors.co/",
    category: "Media",
    description: "The super fast color palettes generator!",
    imageSlug: "coolors",
  },
  {
    name: "Dareful",
    url: "https://dareful.com/",
    category: "Media",
    description: "Completely free 4K stock video footage.",
    imageSlug: "dareful",
  },
  {
    name: "TypeUI",
    url: "https://www.typeui.sh/",
    category: "UI Components",
    description: "UI components and blocks.",
    imageSlug: "typeui",
  },
  {
    name: "Fancy Components",
    url: "https://www.fancycomponents.dev/",
    category: "UI Components",
    description: "Ready to use, fancy React components.",
    imageSlug: "fancy-components",
  },
  {
    name: "Better T Stack",
    url: "https://www.better-t-stack.dev/",
    category: "Resources & Tools",
    description: "A modern full-stack toolkit.",
    imageSlug: "better-t-stack",
  },
  {
    name: "Shark UI",
    url: "https://shark.vini.one/",
    category: "UI Components",
    description: "Modern UI components for web apps.",
    imageSlug: "shark-ui",
  },
  {
    name: "Remocn",
    url: "https://remocn.dev/",
    category: "UI Components",
    description: "Cinematic video components, now copy-pasteable.",
    imageSlug: "remocn",
  },
  {
    name: "NeonBladeUI",
    url: "https://neonbladeui.neuronrush.com/",
    category: "UI Components",
    description:
      "Futuristic React components with neon aesthetics, sharp edges, and total design control.",
    imageSlug: "neonbladeui",
  },
  {
    name: "Shoogle",
    url: "https://shoogle.dev/",
    category: "Resources & Tools",
    description: "Shadcn Search Engine.",
    imageSlug: "shoogle",
  },
  {
    name: "NativeWind",
    url: "https://www.nativewind.dev/",
    category: "Resources & Tools",
    description: "Style your React Native apps using Tailwind CSS.",
    imageSlug: "nativewind",
  },
  {
    name: "ShadcnSpace",
    url: "https://shadcnspace.com/",
    category: "UI Components",
    description: "Extraordinary Shadcn UI blocks, components, and templates.",
    imageSlug: "shadcnspace",
  },
  {
    name: "Skiper-UI",
    url: "https://skiper-ui.com/",
    category: "UI Components",
    description: "Uncommon components for shadcn/ui.",
    imageSlug: "skiper-ui",
  },
  {
    name: "Ui-layouts",
    url: "https://www.ui-layouts.com/",
    category: "UI Components",
    description: "Copy, Paste UI Components, & Blocks for Developers.",
    imageSlug: "ui-layouts",
  },
  {
    name: "Pixel Perfect UI",
    url: "https://www.pixel-perfect.space/",
    category: "UI Components",
    description: "A pixel-perfect React component library for modern web apps.",
    imageSlug: "pixel-perfect-ui",
  },
  {
    name: "soundcn",
    url: "https://www.soundcn.xyz/",
    category: "Media",
    description: "Curated UI sounds for Copy. Paste. Play.",
    imageSlug: "soundcn",
  },
  {
    name: "Chánh Đại",
    url: "https://chanhdai.com/components",
    category: "UI Components",
    description: "Pixel-perfect, uniquely crafted components by Chánh Đại.",
    imageSlug: "chanh-dai",
  },
];
